[workspace]
members = ["core", "assembly", "valida"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3


[workspace.dependencies]
p3-air = { git = "https://github.com/Plonky3/Plonky3" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3" }

curta-core = { path = "core" }
valida-isa = { path = "valida" }
