[workspace]
[package]
version = "0.1.0"
name = "fibonacci-script"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
bincode = "1.3.3"
log = "0.4.21"
sp1-sdk = { path = "../../../sdk" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
dotenv = "0.15.0"

[build-dependencies]
sp1-helper = { path = "../../../helper" }
