[workspace]
[package]
edition = "2021"
name = "fibonacci-io-script"
version = "0.1.0"

[dependencies]
sp1 = {path = "../../../sp1"}
sp1-core = {path = "../../../core"}

[build-dependencies]
sp1-helper = {path = "../../../helper"}
