[workspace]
[package]
version = "0.1.0"
name = "fibonacci-io-script"
edition = "2021"

[dependencies]
sp1-core = { path = "../../../core" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[build-dependencies]
sp1-helper = { path = "../../../helper" }
