[package]
version = "0.1.0"
name = "ed25519-example"
edition = "2021"

[dependencies]
curta-core = { path = "../../core" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
