[workspace]
[package]
version = "0.1.0"
name = "verifier-program"
edition = "2021"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
curta-zkvm = { git = "https://github.com/succinctlabs/vm.git" }
curta-core = { git = "https://github.com/succinctlabs/vm.git" }
