[workspace]
[package]
version = "0.1.0"
name = "verifier-script"
edition = "2021"

[dependencies]
bincode = "1.3.3"
sp1-core = { path = "../../../core" }
tracing = "0.1.40"

[build-dependencies]
sp1-helper = { path = "../../../helper" }
