[package]
name = "sp1-static-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp1-core = { path = "../../core" }
sp1-recursion-macros = { path = "../constgen" }
sp1-recursion = { path = "../primitives" }
p3-baby-bear = { workspace = true }
p3-air = { workspace = true }
p3-field = { workspace = true }
